version: '3'
services:
  app:
    build:
      context: .
    command: bundle exec puma -C config/puma.rb

    volumes:
      - .:/contact_book_app
      - public-data:/contact_book_app/public
      - tmp-data:/contact_book_app/tmp
      - log-data:/contact_book_app/log
    networks:
      - contact_book_app-network
    depends_on:
      - db

  db:
    image: mysql:5.6.51
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: contact_book_app_development
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - contact_book_app-network

  web:
    build:
      context: ./nginx_docker
    volumes:
      - public-data:/contact_book_app/public
      - tmp-data:/contact_book_app/tmp
    ports:
      - "80:80" # ホストからゲストへポートフォワード
    depends_on:
      - app
    networks:
      - contact_book_app-network

volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:

networks:
  contact_book_app-network:
    external: true
