version: '3'
services:
  app:
    build:
      context: .
    command: bundle exec puma -C config/puma.rb

    volumes:
      - .:/picktweet
      - public-data:/picktweet/public
      - tmp-data:/picktweet/tmp
      - log-data:/picktweet/log
    networks:
      - picktweet-network
    depends_on:
      - db

  db:
    image: mysql:5.6.51
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: picktweet_development
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - picktweet-network

  web:
    build:
      context: ./nginx_docker
    volumes:
      - public-data:/picktweet/public
      - tmp-data:/picktweet/tmp
    ports:
      - "80:80" # ホストからゲストへポートフォワード
    depends_on:
      - app
    networks:
      - picktweet-network

volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:

networks:
  picktweet-network:
    external: true
